language: python
python:
    - 3.5

install:
    - pip install --upgrade pipenv
    - pipenv install --three --dev
    - pipenv uninstall django 
    - pipenv install django==1.8.18 

script:
    - pipenv run pytest
