env:
  global: 
    - CC_TEST_REPORTER_ID=81f38c3825291d927d6d4bff2de777a7b786b9ee7038fbbb4bfba75a335248dd

language: python
python:
    - 3.6

install:
    - pip install --upgrade pipenv
    - pipenv run pip install pip==18.0
    - pipenv install --three --dev

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
    - chmod +x cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - pipenv run pytest --cov=.

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
